spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tasks
    username: postgres
    password: paodebatata
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 3000